javascript:input = prompt("DocuFinderJS - April 2025 Update\nSearch engine reconnaisance for indexed documents & MS Office files\nWSTG Scenario ID: WSTG-INFO-01\n\nEnter the target domain: ");
pdf = ("https://www.google.com/search?q=(filetype:pdf | ext:pdf) site:")+input+("&filter=0");
pdfBing = ("https://bing.com/?q=(filetype:pdf | ext:pdf) site:")+input;
ppt = ("https://www.google.com/search?q=(filetype:ppt | ext:ppt | filetype:pptx | ext:pptx) site:")+input+("&filter=0");
pptBing = ("https://bing.com/?q=(filetype:ppt | ext:ppt | filetype:pptx | ext:pptx) site:")+input;
docx = ("https://www.google.com/search?q=(filetype:doc | ext:doc | filetype:docx | ext:docx) site:")+input+("&filter=0");
docBing = ("https://bing.com/?q=(filetype:doc | ext:doc | filetype:docx | ext:docx) site:")+input;
xlsx = ("https://www.google.com/search?q=(filetype:xlsx | ext:xlsx | filetype:xls | ext:xls | filetype:csv | ext:csv) site:")+input+("&filter=0");
xlsBing = ("https://bing.com/?q=(filetype:xls | ext:xls | filetype:xlsx | ext:xlsx) site:")+input;
function GetDocs() {
    window.open(pdf);
    window.open(pdfBing);
    window.open(ppt);
    window.open(pptBing);
    window.open(docx);
    window.open(docBing);
    window.open(xlsx);
    window.open(xlsBing);
};
GetDocs();